---
num_spines: 2

root_pw_encrypted:
    "$1$q5omhfKL$hZReT1C2OXkuVc7MyeM7C/"

admin_user:
    name: admin
    pw_encrypted: "$1$q5omhfKL$hZReT1C2OXkuVc7MyeM7C/"

mgt:
    prefix: 192.168.122
    default_route: 192.168.0.0/16
    default_nh: 192.168.122.1

leaf_lo_prefix: 192.168.254

spine_lo_prefix: 192.168.255

spine1:
    node_id: 11

spine2:
    node_id: 12

spine3:
    node_id: 13

spine4:
    node_id: 14

site_asn: 64700

vlans:
    - name: v100
      vid: 100
      vni: 10100

    - name: v101
      vid: 101
      vni: 10101
