---
# build_dcf.pb.yml
#   Ansible playbook to build a data center fabric.
#   All-in-one for now, but it probably makes sense to have separate
#   playbooks for leaf, spine, and edge.  We'll get there...
#
#   Also, this pb just builds static configs.  You can push them -- either
#   to a specific device or to a ZTP server -- with another pb.

# =========================================================
# Setup variables and directories
# =========================================================

- name: Creating build directories for each host
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - set_fact:
        build_dir: "{{ build_dir }}/{{ inventory_hostname }}/tmp"
        junos_conf: "{{ build_dir }}/{{ inventory_hostname}}/junos.conf"
    - name: remove host build temp directory
      file: path={{ build_dir }} state=absent
    - name: create host build temp directory
      file: path={{ build_dir }} state=directory

# =========================================================
# Role based config template building
# =========================================================

- name: Call role to build the leaf switch configurations
  hosts: leaf
  connection: local
  gather_facts: no
  roles:
    - dcf_leaf

- name: Call role to build the spine switch configurations
  hosts: spine
  connection: local
  gather_facts: no
  roles:
    - dcf_spine

# =========================================================
# Finish by assembling config snippets into single file
# =========================================================

- name: Creating final junos.conf
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: assembling configfurations
      assemble: src={{ build_dir }} dest={{ junos_conf }}
